annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.4.1
dependencies:
  - condition: memcached.enabled
    name: memcached
    repository: https://charts.bitnami.com/bitnami
    version: 6.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Grafana Tempo is a distributed tracing system that has out-of-the-box integration with Grafana. It is highly scalable and works with many popular tracing protocols.
engine: gotpl
home: https://github.com/grafana/tempo/
icon: https://bitnami.com/assets/stacks/grafana-tempo/img/grafana-tempo-stack-220x234.png
keywords:
  - grafana
  - tracing
  - metrics
  - infrastructure
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: grafana-tempo
sources:
  - https://github.com/bitnami/bitnami-docker-grafana-tempo
  - https://github.com/grafana/tempo/
version: 1.3.1
