annotations:
  category: CMS
apiVersion: v2
appVersion: 9.3.16
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Drupal is one of the most versatile open source content management systems in the world. It is pre-configured with the Ctools and Views modules, Drush and Let's Encrypt auto-configuration support.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/drupal
icon: https://bitnami.com/assets/stacks/drupal/img/drupal-stack-220x234.png
keywords:
  - drupal
  - cms
  - blog
  - http
  - web
  - application
  - php
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: drupal
sources:
  - https://github.com/bitnami/bitnami-docker-drupal
  - https://www.drupal.org/
version: 12.2.11
