helm install aws-ebs-csi-driver .\aws-ebs-csi-driver
helm install aws-efs-csi-driver .\aws-efs-csi-driver
helm install aws-for-fluent-bit .\aws-for-fluent-bit
helm install aws-load-balancer-controller .\aws-load-balancer-controller
helm install aws-node-termination-handler .\aws-node-termination-handler
helm install cluster-autoscaler .\cluster-autoscaler
helm install ingress-nginx .\ingress-nginx
helm install k8s-aws-ebs-tagger .\k8s-aws-ebs-tagger
helm install k8s-event-logger .\k8s-event-logger
helm install kong .\kong
helm install kube-state-metrics .\kube-state-metrics
