helm uninstall airflow
helm uninstall apache
helm uninstall argo-cd
helm uninstall argo-workflows
helm uninstall aspnet-core
helm uninstall cassandra
helm uninstall cert-manager
helm uninstall common
helm uninstall concourse
helm uninstall consul
helm uninstall contour
helm uninstall contour-operator
helm uninstall discourse
helm uninstall dokuwiki
helm uninstall drupal
helm uninstall ejbca
helm uninstall elasticsearch
helm uninstall etcd
helm uninstall external-dns
helm uninstall fluentd
helm uninstall geode
helm uninstall ghost
helm uninstall grafana
helm uninstall grafana-loki
helm uninstall grafana-operator
helm uninstall grafana-tempo
helm uninstall haproxy
helm uninstall haproxy-intel
helm uninstall harbor
helm uninstall influxdb
helm uninstall jasperreports
helm uninstall jenkins
helm uninstall joomla
helm uninstall jupyterhub
helm uninstall kafka
helm uninstall keycloak
helm uninstall kiam
helm uninstall kibana
helm uninstall kong
helm uninstall kube-prometheus
helm uninstall kube-state-metrics
helm uninstall kubeapps
helm uninstall kubernetes-event-exporter
helm uninstall logstash
helm uninstall magento
helm uninstall mariadb
helm uninstall mariadb-galera
helm uninstall mediawiki
helm uninstall memcached
helm uninstall metallb
helm uninstall metrics-server
helm uninstall minio
helm uninstall mongodb
helm uninstall mongodb-sharded
helm uninstall moodle
helm uninstall mxnet
helm uninstall mysql
helm uninstall nats
helm uninstall nginx
helm uninstall nginx-ingress-controller
helm uninstall nginx-intel
helm uninstall node
helm uninstall node-exporter
helm uninstall oauth2-proxy
helm uninstall odoo
helm uninstall opencart
helm uninstall osclass
helm uninstall owncloud
helm uninstall parse
helm uninstall phpbb
helm uninstall phpmyadmin
helm uninstall pinniped
helm uninstall postgresql
helm uninstall postgresql-ha
helm uninstall prestashop
helm uninstall pytorch
helm uninstall rabbitmq
helm uninstall rabbitmq-cluster-operator
helm uninstall redis
helm uninstall redis-cluster
helm uninstall redmine
helm uninstall sealed-secrets
helm uninstall solr
helm uninstall sonarqube
helm uninstall spark
helm uninstall spring-cloud-dataflow
helm uninstall suitecrm
helm uninstall tensorflow-resnet
helm uninstall thanos
helm uninstall tomcat
helm uninstall wavefront
helm uninstall wavefront-adapter-for-istio
helm uninstall wavefront-hpa-adapter
helm uninstall wavefront-prometheus-storage-adapter
helm uninstall wildfly
helm uninstall wordpress
helm uninstall wordpress-intel
helm uninstall zookeeper
