annotations:
  category: Analytics
apiVersion: v2
appVersion: 0.57.0
dependencies:
  - condition: exporters.enabled,exporters.node-exporter.enabled
    name: node-exporter
    repository: https://charts.bitnami.com/bitnami
    version: 3.x.x
  - condition: exporters.enabled,exporters.kube-state-metrics.enabled
    name: kube-state-metrics
    repository: https://charts.bitnami.com/bitnami
    version: 3.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Prometheus Operator provides easy monitoring definitions for Kubernetes services and deployment and management of Prometheus instances.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus
icon: https://bitnami.com/assets/stacks/prometheus-operator/img/prometheus-operator-stack-220x234.png
keywords:
  - prometheus
  - alertmanager
  - operator
  - monitoring
kubeVersion: '>= 1.16.0-0'
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: kube-prometheus
sources:
  - https://github.com/bitnami/bitnami-docker-prometheus-operator
  - https://github.com/bitnami/bitnami-docker-prometheus
  - https://github.com/bitnami/bitnami-docker-alertmanager
  - https://github.com/prometheus-operator/kube-prometheus
version: 8.0.8
