annotations:
  category: E-Commerce
apiVersion: v2
appVersion: 1.7.8-6
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: PrestaShop is a powerful open source eCommerce platform used by over 250,000 online storefronts worldwide. It is easily customizable, responsive, and includes powerful tools to drive online sales.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/prestashop
icon: https://bitnami.com/assets/stacks/prestashop/img/prestashop-stack-220x234.png
keywords:
  - prestashop
  - e-commerce
  - http
  - web
  - php
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: prestashop
sources:
  - https://github.com/bitnami/bitnami-docker-prestashop
  - https://prestashop.com/
version: 15.2.9
