annotations:
  category: CertificateAuthority
apiVersion: v2
appVersion: 7.4.3-2
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    tags:
      - ejbca-database
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: EJBCA is an enterprise class PKI Certificate Authority software, built using Java (JEE) technology.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/ejbca
icon: https://bitnami.com/assets/stacks/ejbca/img/ejbca-stack-220x234.png
keywords:
  - ejbca
  - ca
  - pki
  - certificate
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: ejbca
sources:
  - https://github.com/bitnami/bitnami-docker-ejbca
  - https://www.ejbca.org/
version: 6.2.8
