annotations:
  category: E-Learning
apiVersion: v2
appVersion: 4.0.1
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
description: Moodle(TM) LMS is an open source online Learning Management System widely used at universities, schools, and corporations. It is modular and highly adaptable to any type of online learning.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/moodle
icon: https://bitnami.com/assets/stacks/moodle/img/moodle-stack-220x234.png
keywords:
  - moodle
  - learning
  - php
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: moodle
sources:
  - https://github.com/bitnami/bitnami-docker-moodle
  - https://www.moodle.org/
version: 14.1.9
