annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.6.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: HAProxy is a TCP proxy and a HTTP reverse proxy. It supports SSL termination and offloading, TCP and HTTP normalization, traffic regulation, caching and protection against DDoS attacks.
engine: gotpl
home: https://www.haproxy.org/
icon: https://bitnami.com/assets/stacks/haproxy/img/haproxy-stack-220x234.png
keywords:
  - haproxy
  - proxy
  - infrastructure
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: haproxy
sources:
  - https://github.com/bitnami/bitnami-docker-haproxy
  - https://github.com/haproxytech/haproxy
version: 0.3.28
