## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section HAProxy chart parameters
## Parameters for the bitnami/haproxy chart deployed by this chart
## For a full list, see: https://github.com/bitnami/charts/tree/master/bitnami/haproxy
## Note that parameters from the bitnami/haproxy chart should be prefixed with 'haproxy.'
##

## @param haproxy.image.registry HAProxy image registry
## @param haproxy.image.repository HAProxy image repository
## @param haproxy.image.tag HAProxy image tag (immutable tags are recommended)
## @param haproxy.image.pullPolicy HAProxy image pull policy
## @param haproxy.image.pullSecrets HAProxy image pull secrets
##
haproxy:
  image:
    registry: docker.io
    repository: bitnami/haproxy-intel
    tag: 2.6.1-debian-11-r0
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
