apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-locator-hl" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: locator
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.locator.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.locator.service.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.locator.service.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: locator
      port: {{ .Values.locator.service.ports.locator }}
      targetPort: locator
    - name: http
      port: {{ .Values.locator.service.ports.http }}
      targetPort: http
    - name: rmi
      port: {{ .Values.locator.service.ports.rmi }}
      targetPort: rmi
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: locator
