annotations:
  category: Database
apiVersion: v2
appVersion: 14.4.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
description: This PostgreSQL cluster solution includes the PostgreSQL replication manager, an open-source tool for managing replication and failover on PostgreSQL clusters.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha
icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
keywords:
  - postgresql
  - repmgr
  - pgpool
  - postgres
  - database
  - sql
  - replication
  - cluster
  - high availability
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: postgresql-ha
sources:
  - https://github.com/bitnami/bitnami-docker-postgresql
  - https://www.postgresql.org/
version: 9.1.9
