annotations:
  category: Forum
apiVersion: v2
appVersion: 3.3.7
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
description: phpBB is a popular bulletin board that features robust messaging capabilities such as flat message structure, subforums, topic split/merge/lock, user groups, full-text search, and attachments.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/phpbb
icon: https://bitnami.com/assets/stacks/phpbb/img/phpbb-stack-220x234.png
keywords:
  - phpbb
  - forum
  - http
  - php
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: phpbb
sources:
  - https://github.com/bitnami/bitnami-docker-phpbb
  - https://www.phpbb.com/
version: 12.2.9
