annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.21.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Contour is an open source Kubernetes ingress controller that works by deploying the Envoy proxy as a reverse proxy and load balancer.
home: https://github.com/bitnami/charts/tree/master/bitnami/contour
icon: https://bitnami.com/assets/stacks/contour/img/contour-stack-220x234.png
keywords:
  - ingress
  - envoy
  - contour
maintainers:
  - name: cellebyte
    url: https://github.com/Cellebyte
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: contour
sources:
  - https://github.com/projectcontour/contour
  - https://github.com/envoyproxy/envoy
  - https://github.com/bitnami/bitnami-docker-contour
  - https://projectcontour.io
version: 8.0.3
