annotations:
  category: WorkFlow
apiVersion: v2
appVersion: 2.3.2
dependencies:
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.x.x
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Apache Airflow is a tool to express and execute workflows as directed acyclic graphs (DAGs). It includes utilities to schedule tasks, monitor task progress and handle task dependencies.
home: https://github.com/bitnami/charts/tree/master/bitnami/airflow
icon: https://bitnami.com/assets/stacks/airflow/img/airflow-stack-220x234.png
keywords:
  - apache
  - airflow
  - workflow
  - dag
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: airflow
sources:
  - https://github.com/bitnami/bitnami-docker-airflow
  - https://airflow.apache.org/
version: 12.5.10
