annotations:
  category: E-Commerce
apiVersion: v2
appVersion: 3.0.3-8
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: OpenCart is free open source ecommerce platform for online merchants. OpenCart provides a professional and reliable foundation from which to build a successful online store.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/opencart
icon: https://bitnami.com/assets/stacks/opencart/img/opencart-stack-220x234.png
keywords:
  - opencart
  - e-commerce
  - http
  - web
  - php
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: opencart
sources:
  - https://github.com/bitnami/bitnami-docker-opencart
  - https://opencart.com/
version: 12.2.9
