annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.4.2
dependencies:
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Argo CD is a continuous delivery tool for Kubernetes based on GitOps.
engine: gotpl
home: https://argoproj.github.io/argo-cd/
icon: https://bitnami.com/assets/stacks/argo-cd/img/argo-cd-stack-220x234.png
keywords:
  - Continuous delivery
  - Continuous deployment
  - Devops
  - Kubernetes
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: argo-cd
sources:
  - https://github.com/bitnami/bitnami-docker-argo-cd
  - https://github.com/argoproj/argo-cd/
  - https://github.com/bitnami/bitnami-docker-dex
  - https://github.com/dexidp/dex
version: 3.4.3
