annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 8.0.2
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: JasperReports Server is a stand-alone and embeddable reporting server. It is a central information hub, with reporting and analytics that can be embedded into web and mobile applications.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/jasperreports
icon: https://bitnami.com/assets/stacks/jasperserver/img/jasperserver-stack-220x234.png
keywords:
  - business intelligence
  - java
  - jasper
  - reporting
  - analytic
  - visualization
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: jasperreports
sources:
  - https://github.com/bitnami/bitnami-docker-jasperreports
  - http://community.jaspersoft.com/project/jasperreports-server
version: 14.1.10
