annotations:
  category: CMS
apiVersion: v2
appVersion: 4.1.5
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
description: Joomla! is an award winning open source CMS platform for building websites and applications. It includes page caching, page compression and Let's Encrypt auto-configuration support.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/joomla
icon: https://bitnami.com/assets/stacks/joomla/img/joomla-stack-220x234.png
keywords:
  - joomla
  - cms
  - blog
  - http
  - php
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: joomla
sources:
  - https://github.com/bitnami/bitnami-docker-joomla
  - https://www.joomla.org/
version: 13.2.11
